version: "3.3"

services:
  calmerge:
    build: .
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=production
      - NODE_PORT=3012
    volumes:
      - ./calendar:/app/calendar
      - ./logs:/app/logs
    restart: unless-stopped
